### ISSUE TITLE
[Bug]: Vehicle model generator not compatible with latest VSS Tools

### ISSUE THREAD

**Issue by DocMoebiuz** [eclipse-velocitas/vehicle-model-generator#4]
### What happened?

After a recent update of the VSS Tools the Vehicle Model Generator script fails with two errors:

1. TypeError: load_tree() got an unexpected keyword argument 'break_on_noncore_attribute'
2. AttributeError: 'VSSNode' object has no attribute 'data_type'

Steps to reproduce:
* Clone repo
* Download latest VSS spec
* Try to build the model as outlined in the README.md

Expected result:
* Model is built using latest VSS specs

Actual result:
* Error messages are displayed

Background:
https://github.com/COVESA/vss-tools/commit/088791c15ac6afc18389e6446c06d1e33bd62032#diff-bd7a7e19458ea183d09243c6b66711908091c977580d1564a1c9f4e6e7c0c63aL93 renamed the parameter for `load_tree`

`node.data_type` was renamed to `node.datatype`

### Operating System

macOS (Default)

### What release version or branch did you use?

latest

### Relevant log output

```shell
python3 gen_vehicle_model.py -I ./vehicle_signal_specification/spec ./vehicle_signal_specification/spec/VehicleSignalSpecification.vspec 
Loading vspec...
Traceback (most recent call last):
  File "/workspaces/vehicle-app-python-template/repos/vehicle-model-generator/gen_vehicle_model.py", line 87, in <module>
    tree = vspec.load_tree(
TypeError: load_tree() got an unexpected keyword argument 'break_on_noncore_attribute'


python3 gen_vehicle_model.py -I ./vehicle_signal_specification/spec ./vehicle_signal_specification/spec/VehicleSignalSpecification.vspec
Loading vspec...
Recursing tree and creating Python code...
Traceback (most recent call last):
  File "/workspaces/vehicle-app-python-template/repos/vehicle-model-generator/gen_vehicle_model.py", line 98, in <module>
    VehicleModelPythonGenerator(
  File "/workspaces/vehicle-app-python-template/repos/vehicle-model-generator/python_generator.py", line 109, in generate
    self.__gen_model(self.root, path, True)
  File "/workspaces/vehicle-app-python-template/repos/vehicle-model-generator/python_generator.py", line 213, in __gen_model
    self.__gen_model_docstring(node)
  File "/workspaces/vehicle-app-python-template/repos/vehicle-model-generator/python_generator.py", line 188, in __gen_model_docstring
    self.ctx.write(f"{i.name}: {i.type.value} ({i.data_type.value})\n")
AttributeError: 'VSSNode' object has no attribute 'data_type'
```

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by emsameen** [comment]
Fixed and integrated
