### ISSUE TITLE
there is bug when running cli.py

### ISSUE THREAD

**Issue by tuanzimplistic** [eclipse-velocitas/vehicle-model-generator#57]
Here is the log:
    from velocitas.model_generator import generate_model
ModuleNotFoundError: No module named 'velocitas'

**Comment by dennismeister93** [comment]
Hi @tuanzimplistic :)

Thanks for trying out and experimenting with the programming language of python and our provided vehicle-model-generator.

In our [quickstarting guide](https://eclipse.dev/velocitas/docs/tutorials/quickstart/quickstart/) we are recommending to use the vscode feature which is called "DevContainers".
This feature allows you to get started quickly without having to worry about setting up a working development environment.

Although your reported issue is not really telling us much of how you reached that state of failure, I assume that you did not correctly setup your environment of execution.

If you prefer running the vehicle-model-generator on your local development machine please install all required dependencies by yourself:

```
pip3 install -r ./requirements-dev.txt
pip3 install -r ./requirements.txt
pip3 install -e .
```

If this is still not solving your problem i recommend you to make use of a DevContainer!

We are also happy to receive any constructive feedback in form of a PR to improve the usage of our vehicle-model-generator

Try it out and come back to us if you have any other problems.

Kind Regards!

**Comment by thu4n** [comment]
I'm facing this issue as well. I have already run all the pip installation commands but it still didn't work for me (I'm on Ubuntu 22.04). Is DevContainers the only approach for now or is there anything else I can try?

**Comment by dennismeister93** [comment]
@thu4n Can you provide more step by step logs when installing the dependencies and executing the script please?

DevContainer is the recommended approach, but as I already stated it should also work locally

**Comment by thu4n** [comment]
Thank you for the quick reply, below are logs of the error:
```
cd vehicle-model-generator
python3 src/velocitas/model_generator/cli.py ../vss_rel_4.0.json 


Traceback (most recent call last):
  File "/home/dev/ws/vehicle-model-generator/src/velocitas/model_generator/cli.py", line 23, in <module>
    from velocitas.model_generator import generate_model
ModuleNotFoundError: No module named 'velocitas'
```

As for requirements.txt and requirements-dev.txt, they were all successfully installed.

**Comment by dennismeister93** [comment]
please execute this and give us all of the logs:

```
cd vehicle-model-generator
pip3 install -r ./requirements-dev.txt
pip3 install -r ./requirements.txt
pip3 install -e .
python3 src/velocitas/model_generator/cli.py ../vss_rel_4.0.json
```

**Comment by thu4n** [comment]
Here are the logs:
```
cd vehicle-model-generator
pip3 install -r ./requirements-dev.txt
pip3 install -r ./requirements.txt
pip3 install -e .
python3 src/velocitas/model_generator/cli.py ../vss_rel_4.0.json
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pre-commit>=3.5.0 in /home/dev/.local/lib/python3.10/site-packages (from -r ./requirements-dev.txt (line 1)) (3.7.1)
Requirement already satisfied: mypy in /home/dev/.local/lib/python3.10/site-packages (from -r ./requirements-dev.txt (line 2)) (1.10.1)
Requirement already satisfied: cfgv>=2.0.0 in /home/dev/.local/lib/python3.10/site-packages (from pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (3.4.0)
Requirement already satisfied: virtualenv>=20.10.0 in /home/dev/.local/lib/python3.10/site-packages (from pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (20.26.3)
Requirement already satisfied: identify>=1.0.0 in /home/dev/.local/lib/python3.10/site-packages (from pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (2.5.36)
Requirement already satisfied: nodeenv>=0.11.1 in /home/dev/.local/lib/python3.10/site-packages (from pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (5.4.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/dev/.local/lib/python3.10/site-packages (from mypy->-r ./requirements-dev.txt (line 2)) (4.12.2)
Requirement already satisfied: mypy-extensions>=1.0.0 in /home/dev/.local/lib/python3.10/site-packages (from mypy->-r ./requirements-dev.txt (line 2)) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /home/dev/.local/lib/python3.10/site-packages (from mypy->-r ./requirements-dev.txt (line 2)) (2.0.1)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/dev/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (0.3.8)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /home/dev/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (4.2.2)
Requirement already satisfied: filelock<4,>=3.12.2 in /home/dev/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit>=3.5.0->-r ./requirements-dev.txt (line 1)) (3.15.4)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vss-tools==4.0 in /home/dev/.local/lib/python3.10/site-packages (from -r ./requirements.txt (line 1)) (4.0)
Requirement already satisfied: graphql-core in /home/dev/.local/lib/python3.10/site-packages (from vss-tools==4.0->-r ./requirements.txt (line 1)) (3.2.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from vss-tools==4.0->-r ./requirements.txt (line 1)) (5.4.1)
Requirement already satisfied: anytree>=2.8.0 in /home/dev/.local/lib/python3.10/site-packages (from vss-tools==4.0->-r ./requirements.txt (line 1)) (2.12.1)
Requirement already satisfied: deprecation>=2.1.0 in /home/dev/.local/lib/python3.10/site-packages (from vss-tools==4.0->-r ./requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from anytree>=2.8.0->vss-tools==4.0->-r ./requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: packaging in /home/dev/.local/lib/python3.10/site-packages (from deprecation>=2.1.0->vss-tools==4.0->-r ./requirements.txt (line 1)) (24.1)
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/dev/ws/vehicle-model-generator
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///home/dev/ws/vehicle-model-generator has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
Traceback (most recent call last):
  File "/home/dev/ws/vehicle-model-generator/src/velocitas/model_generator/cli.py", line 23, in <module>
    from model_generator import generate_model
ModuleNotFoundError: No module named 'model_generator'
```

**Comment by dennismeister93** [comment]
I actually cant reproduce this issue. Did you change anything inside "pyproject.toml" ?

**Comment by thu4n** [comment]
No, I did not make any change to that file. However, I managed to solve this issue by copying the `velocitas` directory into my global Python path in `.local/lib/`. So I guess that is one possible workaround for now?

**Comment by dennismeister93** [comment]
Yes thats one manual workaround, but in general it seems that your python and dependency installation on your local environment is having issues -> (Yet another reason to use devcontainers :) )
